# Generated by Django 3.2.2 on 2023-04-09 01:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20230409_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_plan',
            name='drm_limit_per_user',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='premium_plan',
            name='drm_limit_per_user',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='basic_plan',
            name='max_recovery_days',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='basic_plan',
            name='no_of_users',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='group_logs',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 1, 24, 3, 270649)),
        ),
        migrations.AlterField(
            model_name='user_logs',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 1, 24, 3, 269649)),
        ),
    ]
