# Generated by Django 3.2.2 on 2023-04-09 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20230409_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_logs',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 1, 52, 20, 466732)),
        ),
        migrations.AlterField(
            model_name='user_logs',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 1, 52, 20, 465753)),
        ),
    ]
