# Generated by Django 3.2.2 on 2023-05-11 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20230410_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_logs',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 13, 32, 0, 676104)),
        ),
        migrations.AlterField(
            model_name='user_logs',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 13, 32, 0, 675700)),
        ),
    ]
