# Generated by Django 3.2.2 on 2023-03-03 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=30, unique=True)),
                ('user_token', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sync_Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_from_id', models.CharField(max_length=50)),
                ('status_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('folder_from_name', models.CharField(max_length=50)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_syncs', to='ftp.server_connection')),
                ('folder_to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_syncs', to='content.folder')),
            ],
        ),
    ]
