# Generated by Django 3.2.2 on 2023-04-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync_direction',
            name='type',
            field=models.CharField(choices=[('gdrive', 'gdrive'), ('onedrive', 'onedrive')], default='onedrive', max_length=10),
        ),
    ]
