# Generated by Django 3.2.2 on 2023-04-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0002_sync_direction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sync_direction',
            name='type',
        ),
        migrations.AddField(
            model_name='server_connection',
            name='type',
            field=models.CharField(choices=[('gdrive', 'gdrive'), ('onedrive', 'onedrive')], default='onedrive', max_length=10),
        ),
    ]
