# Generated by Django 3.2.2 on 2023-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0003_auto_20230402_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_connection',
            name='type',
            field=models.CharField(choices=[('googledrive', 'googledrive'), ('onedrive', 'onedrive')], default='onedrive', max_length=14),
        ),
    ]
