# Generated by Django 3.2.2 on 2023-04-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0004_alter_server_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_connection',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
