# Generated by Django 3.2.2 on 2023-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0005_server_connection_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync_direction',
            name='folder_from_id',
            field=models.CharField(max_length=1000),
        ),
    ]
