# Generated by Django 3.2.2 on 2023-03-03 08:54

import content.utils
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_clamav.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('content', models.FileField(max_length=1000, upload_to=content.utils.upload_path, validators=[django_clamav.validators.validate_file_infection])),
                ('urlhash', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('last_deleted', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('size', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('urlhash', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('date_modified', models.DateTimeField(default=datetime.datetime(2023, 3, 3, 8, 54, 33, 296703, tzinfo=utc))),
                ('deleted', models.BooleanField(default=False)),
                ('last_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internal_Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_hash', models.CharField(max_length=6, unique=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('has_read', models.BooleanField(default=True)),
                ('can_add_delete_content', models.BooleanField(default=False)),
                ('can_share_content', models.BooleanField(default=False)),
                ('can_download_content', models.BooleanField(default=False)),
                ('is_proctored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Internal_Share_Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_hash', models.CharField(max_length=6, unique=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('has_read', models.BooleanField(default=True)),
                ('can_add_delete_content', models.BooleanField(default=False)),
                ('can_share_content', models.BooleanField(default=False)),
                ('can_download_content', models.BooleanField(default=False)),
                ('is_proctored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Link_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Link_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('access_type', models.CharField(choices=[('employee', 'Employee'), ('client', 'Client')], default='Employee', max_length=20)),
                ('link_hash', models.CharField(max_length=6, unique=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('access_limit', models.IntegerField(null=True)),
                ('link_type', models.CharField(max_length=100)),
                ('is_proctored', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('prevent_forwarding', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
