# Generated by Django 3.2.2 on 2023-03-03 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request_file',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_file',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_recieved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link_model',
            name='file_hash',
            field=models.ManyToManyField(related_name='link_files', to='content.Files_Model'),
        ),
        migrations.AddField(
            model_name='link_model',
            name='folder_hash',
            field=models.ManyToManyField(related_name='link_folders', to='content.Folder'),
        ),
        migrations.AddField(
            model_name='link_model',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link_model',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link_logs',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='content.link_model'),
        ),
        migrations.AddField(
            model_name='link_logs',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internal_share_folders',
            name='folder_hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_link_folders', to='content.folder'),
        ),
        migrations.AddField(
            model_name='internal_share_folders',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_group_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internal_share_folders',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_shared_with_you', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internal_share',
            name='file_hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_link_files', to='content.files_model'),
        ),
        migrations.AddField(
            model_name='internal_share',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internal_share',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_shared_with_you', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files_model',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.folder'),
        ),
        migrations.AddField(
            model_name='files_model',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files_model',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
