# Generated by Django 3.2.2 on 2023-03-07 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_model',
            name='is_favourite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 16, 19, 56, 172290)),
        ),
    ]
