# Generated by Django 3.2.2 on 2023-03-23 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20230307_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 10, 28, 6, 459567)),
        ),
    ]
