# Generated by Django 3.2.2 on 2023-03-28 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_folder_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 21, 5, 52, 80375, tzinfo=utc)),
        ),
    ]
