# Generated by Django 3.2.2 on 2023-03-29 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_folder_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 23, 37, 57, 654494)),
        ),
    ]
