# Generated by Django 3.2.2 on 2023-04-02 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_folder_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 7, 26, 47, 89853)),
        ),
    ]
