# Generated by Django 3.2.2 on 2023-04-07 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_folder_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 1, 54, 45, 731171)),
        ),
    ]
