# Generated by Django 3.2.2 on 2023-04-09 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_folder_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_model',
            name='is_drm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link_model',
            name='uploadinfo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 0, 22, 37, 224979)),
        ),
    ]
