# Generated by Django 3.2.2 on 2023-04-09 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20230409_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 1, 24, 3, 796698)),
        ),
    ]
