# Generated by Django 3.2.2 on 2023-04-09 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_folder_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_model',
            name='uploadinfo',
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 1, 52, 20, 983857)),
        ),
    ]
