# Generated by Django 3.2.2 on 2023-04-10 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20230409_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 5, 4, 6, 160869)),
        ),
        migrations.AlterField(
            model_name='internal_share',
            name='file_hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_link_files', to='content.files_model'),
        ),
        migrations.AlterField(
            model_name='internal_share_folders',
            name='folder_hash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_link_folders', to='content.folder'),
        ),
    ]
