# Generated by Django 3.2.2 on 2023-05-11 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20230410_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 13, 32, 0, 845361)),
        ),
        migrations.AlterField(
            model_name='link_logs',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='content.link_model'),
        ),
    ]
